import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sidebar";
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex h-screen w-screen`}>
        <Sidebar />
        <div className=" h-screen overflow-hidden w-[75vw] flex flex-col">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
